# Define a imagem Docker que será usada para construir o aplicativo
image: node:lts

# Funções que devem ser executadas antes do script de construção
before_script:
  - npm install

# Definição das configurações para a implantação do GitLab Pages
pages:
  script:
    # Comando para construir o aplicativo
    - npm run build -- --prod
  artifacts:
    # Define os arquivos que serão expostos na URL da página
    paths:
      - dist/agbara-capoeira
  rules:
    # Esta regra garante que apenas commits no branch padrão acionarão
    # a implantação das páginas
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
