# Define a imagem Docker que será usada para construir o aplicativo
image: node:lts

stages:
  - build
  - deploy

# Job de build
build:
  stage: build
  script:
    - npm install -g @angular/cli
    - npm install # ou o comando que você usa para instalar dependências
    - npm run build --prod --base-href /agbara-capoeira/  # ou o comando que você usa para buildar o projeto
  artifacts:
    paths:
      - public/ # Certifique-se de que esta é a pasta onde os arquivos estáticos são gerados

# Job de deploy para o GitLab Pages
pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - main # Ou a branch que você usa para deploy
    - pages
